services:
  # Servicio de la aplicaci√≥n Node.js ( Backend )
  app:
    container_name: ${APP_CONTAINER_NAME}
    working_dir: /usr/src/app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "${APP_CPU_LIMIT}"
          memory: ${APP_MEM_LIMIT}
    networks:
      - backend
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    ports:
      - "$POSTGRES_PORT:5432"
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data_postu:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "${DB_CPU_LIMIT}"
          memory: ${DB_MEM_LIMIT}
    networks:
      - backend

volumes:
  data_postu:

networks:
  backend:
    driver: bridge
